import 'package:samplee/models/gridmodel.dart';
const biodetails = const [
Category(
  name: 'Jeff Bezos',
  image: 'images/geff.webp',
  qulity: 'Built on the pillars of creativity, single-minded focus and a will to provide the highest consumer experience\n    Success is like an iceberg. You just see the tip of it shining. What you don’t see is the portion under water facing the odd',
  intro: ' Net worth : 187 Billion Dollar\n Bezos Owned Company: Washington Post and Blue Origin Aerospace Company Also Founded   Amazon inc',
  advice: '   Knack for Innovation \n 2.	Hardcore Realist \n 3.	Form a Plan \n 4.	 Risk Taker ',
  carrer: 'Jeff Bezos went onto to build a web retailing system while the world was still wondering how an internet can function. The key focus for Amazon has never been to defeat competitors. Rather it focuses on helping consumers and building a value for them. This keeps them engrossed in implementing their plans and policies,Time magazine awarded Jeff Bezos the title of ‘Person of the Year’ and ‘The King of Cyber Commerce’. The remarkable thing is that Bezos was the fourth youth to receive the award at the age of 35. In 2008 Bezos was awarded an honorary doctorate in science and technology from Carnegie Mellon University Amazon is the largest Internet company by revenue in the world and the second-largest employer in the United States.',
  life: 'Bezos quit D.E. Shaw in 1994 and moved to Seattle to tap into the potentials of the internet market by opening an online bookstore. He made the decision by drawing up a list of possible products that he could sell via the Internet, including CDs, software, and hardware. In the end, books were the obvious choice because of the wide range of titles in existence. Another advantage of an internet store was a then-recent U.S. Supreme Court ruling that mail-order catalogs did not have to pay taxes in states where they did not have a physical presence. In other words – Bezos paid zero tax for the products he sold via the internet.The Washington Post is one of the largest newspapers in America and is also owned by Jeff Bezos apart from Amazon. This media firm is 141 years old, and Jeff bought it for about  230 million dollar. ',

),
Category(
  name: 'Elon Musk',
  image: 'images/musk.jpg',
  qulity: '\n Making mistakes is not scary. It’s important to make mistakes in something new.\n Creating a good company is similar to baking a pie. You just need the right ingredients in the right proportions.\n Many of us don’t like changes, but we must learn to accept them. Especially if the alternative to changes is a disaster.\n It is very important that you like the people you work with, otherwise, life and work will be rather unhappy.\n If something is really important to you, even if everything is against you, you should still do it.\n There is a bias towards risk. Everyone is trying too hard to cover all the angles.\n I would like to die on Mars, but not crashing into its surface.\n Persistence is very important. You must not give up unless you are forced to give up.\n I think ordinary people can choose to be unusual.\n I can either watch this happen or be part of it',
  intro: 'Elon Musk Owned Company  : Tesla Inc,  SpaceX, Neuralink,\n   When something is important enough, you do it even if the odds are not in your favour',
  life: 'Being the Firstborn of a South African father and a Canadian mother who got divorced when he was 9 by the way. He is always interested in books. His dad said, “he used to read books even while he was at a party.” He taught himself programming and developed a game at the age of 12 and sold it to a company for a price of 500 dollar.In Canada to survive poverty he worked in some low paid jobs, then he received a scholarship from The University of Pennsylvania and moved to the United States. Elon Musk majored in Physics and Economics, yup two bachelor degrees',
  carrer: 'In 2004, Elon Musk was institutional in designing the first electric car of Tesla named as “The Tesla Roadster”. Under the watch of the big billionaire, Tesla has risen to become the world’s most popular and desirable car brands. Musk claims 2008 as the worst year of his life. With the financial crisis, Elon Musk was broke, and he also had to bring out Tesla from the massive debt, and along with that, he was undergoing a divorce',
  advice: ' Do Not Take Constructive Criticism Personally\n Get Your Hands Dirty\n Don t Let Anybody Tell You No\n Don t Focus on Money\n Be Realistic',

),
Category(
  name: 'Jack Ma ',
  image: 'images/jack.jpg',
  qulity: ' Get Used To Rejection\n Keep Your Dream Alive\n Focus On Culture\n Ignore The Littleman\n Get Inspired\n Stay Focused\n Don’t Complain, Look For Opportunities',
  intro: '“We keep fighting. We keep changing ourselves. We don’t complain.” \n Jack Ma is the founder of the E-commerce giant Alibaba and is a stakeholder at Alipay, it’s sister company which is an e-payment portal. He is now officially the richest man in China with an estimated net worth of 25 Billion dollar',
  life: 'Jack Ma was born on 10 September 1979 in a very small village in China. He saw every face of childhood poverty that is difficult for us to even imagine.\n He was very interested in learning and understanding the English language from childhood. At that time, the main language of the communist country China was Chinese and in the 70s, Chinese language was given importance. No special attention was given to learning and studying the English language, nor was it considered necessary.',
  carrer: 'After doing government work for a few days, he came back to the village and agreed to invest 18 of his friends. And thus together with his friends he laid the foundation of an “Alibaba” company (a startup at the time).\n  In the initial phase, the office of this company built its own apartment. These days he had no other capital other than the investment of his friends, but later by 19, with the help of some other companies, his investment increased to  25 million dollar.',
  advice: ' It does not matter that I failed. At least I passed the concept to others. Even if I don’t succeed, someone else will succeed.\n No matter how tough the past is, you should always have the dream you saw the day before. He will keep you motivated and save you.\n When we have money, then we start making mistakes.\n You do not know how much you can do in your life.\n If you have never tried, how will you know that there is a chance?',
),
Category(
  name: 'Bill Gates ',
  image: 'images/billgates.webp',
  qulity: ' Never Stop Learning\n Setbacks Are Your Best Teachers\n Trust That The World Is Getting Better And That It Can Be Improved Even Further',
  intro: '“I would try and make myself more self-aware without getting rid of the focus and desire to learn.”\n  Bill Gates is the co-founder of Microsoft Corporation. Bill Gates is an American programmer, entrepreneur, investor and philanthropist, co-founder of Microsoft: the premier software company in the world',
  life: 'Gates was born William Henry Gates III on October 28, 1955, in Seattle, Washington. Gates grew up in an upper-middle-class family with his older sister, Kristianne, and younger sister, Libby. At the early age of 13, a passion for computers and programming was developed by Bill Gates. He also got himself enrolled into a private preparatory school, the Lakeside School at the same age. While at school, seeing Gates’ flare in programming, the school administration decided to buy him a computer from the General Electric Company. The school administration allowed him to pursue his interest by excusing him from classes. Bill Gates, on the GEC machine, built his first ever computer program.',
  carrer: 'Bill Gates and Paul Allen, in 1975, co-founded a software company that was named as Micro-Soft. In the initial stage, the company was delivering small software products to different firms as they were not able to hire a sales manager. This process was done by Gates’ mother, Mary Maxwell.\n   Shortly thereafter, the company started to face financial crises that made Gates and Allen realize that Microsoft had dropped to the lowest affordable point. The issue was occurring mainly due to the usage of some pirated software. However, the two owners had the courage not to lose hope and as “Struggling is a Part of the Story”, both of them came up with the launch of MS-BASIC, which helped them in making a profit of 50,000 dollar',
  advice: '. Start as Early as Possible\n Be Your Own Boss as Soon as Possible\n Be Committed and Passionate\n Be Ready to Takes Risks\n Never Fast Forward Your Way to Success\n Be Proud of Who You Are\n Take Things Positively & Love Learning\n Accept Failures & Move On',

),
Category(
  name: 'Steve Jobs ',
  image: 'images/stevejobs.jpg',
  qulity: 'Steve Jobs’ story is one of a kind. It had lots of ups and downs. Right from becoming the co-founder of Apple, to being thrown out of it, he has endured it all.',
  intro: '\n Do what you love.\n Put a dent in the universe\n Make connections\n Say no to 1,000 things.\n Create insanely different experiences\n Sell dreams, not products',
  life: 'At the age of 12, Job called HP founder Bill Hewlett to ask for electronic parts for a school project. This impressed Hewlett so much that he gave him a job as a summer intern. He never enjoyed going to school. The only subject which he was interested in attending his school was Calligraphy. He said about the course, “ If I had never dropped in on that single calligraphy course in college, the Mac would have never had multiple typefaces or proportionally spaced fonts." His first job was in a video manufacturing company called ‘ Atari’. He saved up from his salary and went to India with his friend for spiritual enlightenment. He was in India for 7 months travelling in buses in Delhi, UP and Himachal Pradesh. His major career breakthrough came when he teamed with Steve Wozniak to start the world’s largest IT company, “ Apple”.',
  carrer: 'Steve Jobs teamed up with Steve Wozniak, whom he had met in his summer internship to start the blue box which was a digital box to make long-distance calls for free. The success of Blue Box led to the invention of Apple I. Jobs sold his Volkswagen microbus and Wozniak sold off his calculator to generate 1350 dollar. With this, they started Apple I. It was a kit for building in which the user needed to add the monitor and keyboard. The too later gathered enough investment to find Apple II. Apple II was a huge success. The first-year sales topped  3million dollar. Two years later sales soared up to 200 million dollar. Apple II  made the company Apple. Apple was officially incorporated in 1977.',
  advice: 'Obstacles Are Opportunities in Disguise\n Surround Yourself with Great People\n Learn How to Anticipate the Future\n Remember You Will Be Dead Soon\n Focus on the Positive\n Find the Right Partner\n Learn From Others\n Travel the World\n Fail Forward\n Take Risks',

),
Category(
  name: 'Ratan Tata ',
  image: 'images/ratantata.jpg',
  qulity: ' A visionary Leader\n Ability to motivate others\n Humility\n A  man with Positive taker\n Risk Taker',
  intro: 'I dont believe in taking the right decisions, I take decisions and then make them right.\n   A man who has made his mark in this so deep, that every aspiring entrepreneur looks up to him as a role model. He is very well known not only for his way and tactics of doing business, but also for his ethical ways of managing every business operation',
  life: 'MR. TATA came into the world on December 28, 1937 in the city of Surat, India. Ratan Tata’s father was MR. Naval Tata and mother was Mrs. Sonoo Tata. He has a younger brother named Jimmy and a step brother as well named Noel Tata\nEven after his parents being separated, both his father and mother made time to meet their children Ratan Tata and Jimmy, but never came together again, as a family.\n This had a deep negative impact on both the children. However, Ratan Tata was being looked after by his grandmother, Lady Navajbai Tata in Mumbai',
  carrer: 'NALCO was one of the largest electronics companies in India. But when Ratan Tata overtook him as the SA director in charge, NALCO was running at a huge loss, with only 2% share in the industry.\n  NALCO was running in Loss’s at the time because electronic things were being updated in a new way, which it did not accept. Then Ratan Tata realized that you have to start from the beginning and in a word, TCS ( Tata Consultancy Services) was starting.',
  advice: ' Ups and Downs are more important\n Prove yourself\n Nothing is free\n Teacher is better than Boss\n No Second Change\n Come out from virtual life\n Be humble to everyone',

),
Category(
  name: 'Mark Zuckerberg',
  image: 'images/markk.webp',
  qulity: ' Mark Zuckerberg Manages his Time\n Setting Challenges\n Stick to your Passion\n Focus on One Thing\n Have a Dream\n Learn to Take Risks',
  intro: 'Mark Zuckerberg is co-founder and CEO of the social-networking website Facebook, as well as one of the worlds youngest billionaires.What can a boy do at the young age of 19? The answer is, “A lot!” And something similar was seen by Mark Zuckerberg, as he made Facebook with his friends at a young age. Let us know in detail the life of Mark Zuckerberg, one of the youngest billionaires in the world today',
  life: 'Zuckerberg was born on May 14, 1984, in White Plains, New York, into a comfortable, well-educated family. He was raised in the nearby village of Dobbs Ferry.Zuckerberg’s father, Edward Zuckerberg, ran a dental practice attached to the familys home. His mother, Karen, worked as a psychiatrist before the birth of the couples four children — Mark, Randi, Donna and Arielle.',
  carrer: 'To keep up with Zuckerberg burgeoning interest in computers, his parents hired private computer tutor David Newman to come to the house once a week and work with Zuckerberg. Newman later told reporters that it was hard to stay ahead of the prodigy, who began taking graduate courses at nearby Mercy College around this same time.Yet Zuckerberg remained fascinated by computers and continued to work on developing new programs. While still in high school, he created an early version of the music software Pandora, which he called Synapse.',
  advice: 'Be Passionate About What You Do\n Set High and Long-Term Goals\n Move Fast and Break Things\n Explore Before You Commit\n Hire the Right People\n Focus on Your Product and Make it Better\n Time is Money\n Stay in Learning Mode All the Time',

),
Category(
  name: 'A.P. J. Abdul Kalam ',
  image: 'images/apjkalam.jpg',
  qulity: 'Have a great aim.\n Continuously acquire knowledge.\n Work hard\n Persevere',
  intro: '“Thinking is the capital, Enterprise is the way, and Hard Work is the solution.”\n  A.P. J. Abdul Kalam (15 October 1931 – 27 July 2015) also known as Missile Man of India. He is highly respected and known for his contribution to aerospace engineering and military missile development efforts. He became the 11th President of India from 2002 to 2007 and is very popular among students. He was awarded the Bharat Ratna, India’s highest civilian honor.',
  life: 'A.P.J Abdul Kalam (15th October 1931- 27 July 2015) born in Rameswaram into a Tamil Muslim family in Tamil Nadu itself. He came from a humble background where his father, a boat owner and mother, a housewife brought him up. He used to distribute newspaper after the completion of his school so that he could support his father. What he had was a yearning to learn more. He was in Ramanathapuram Schwartz Matriculation School and later he went to Saint Joseph’s College from where he became a physics graduate. In 1955 he went to Madras to pursue his studies further in Madras',
  carrer: 'For the Indian army, A.P.J Abdul Kalam designed a mini helicopter. Major breakthrough came when he was transferred to ISRO catering to the project of SLV-III. Being the representative of TBRL, he acted as the representative of Smiling Buddha which was the first nuclear test to be conducted\n   A.P.J Abdul Kalam won the election of President in 2002 by surpassing mammoth votes. His term as President was from 25 July 2002 to 25 July 2007. He was backed by the parties of National Congress and Samajwadi Party. It was an easy victory for him and he became the 11th President of India. He received the highest civilian honour Bharat Ratna and the third person to do so',
  advice: '. Learn How to Handle Failure\n Practice the Art of Giving\n Imagine the Outcome that You Want\n Breakthrough Your Limits\n Fight to be You\n Be A Student\n Be A Teacher\n Work with Integrity\n Follow Your Dreams\n Be the Inspiration',

),
Category(
  name: 'Elon Musk',
  image: 'images/aambani.jpg',
  qulity: ' Always think of how to be revolutionary\n Think big, start small\n You can learn the most from the risks you take\n Bet on the people around you\n Do not worry about change\n Create a niche for yourself',
  intro: '“You will never reach your destination if you stop and throw stones at every stone at every dog that bark… better keep biscuits and move on.”\n   Dhirubhai Ambani, the late founder of Reliance Industries Ltd (RIL), has been primarily credited for the vision and objectives of the oil-to-textile-to-retail-to-telecom conglomerate.',
  life: 'Dhirajlal Hirachand Ambani was born on 28 December 1932 in a small village called Chorwad (Gujarat). He died on 6 July 2002 in Mumbai. Reliance commercial corporation was founded in 1966 as s polyester firm. In 1973 the company got renamed as Reliance industries. Later the company entered into petroleum and financial service.  ',
  carrer: 'Dhirubhai Ambani returned to India in 1958 He started a textile business “Majin” along with his cousin Champaklal. Majin used to export goods like spices and rayon in yamen and import polyester. Dhirubhai Ambani was set up the first office at the Narsinatha Street in Masjid Bunder. The office area was 33-meter square. in a 350 square foot area, Ambani had kept very few and important things like three chairs, one telephone, and one table.\n   In 1956, their partnership (Dhirubhai Ambani and Champaklal) got ended. It believed that both had a different point of view to run a business this is why their partnership didn’t work out very well. Ambani had good marketing knowledge, he was also known as a risk-taker and believed that in building inventories to rise income. In 1966 he launched a company called Reliance Commercial Corporation which later renamed the company, now this company known as Reliance industries.',
  advice: ' Dont give up. Courage is my conviction.\n Think big, think fast, think ahead. Ideas are no ones monopoly.\n If you’re born poor it’s not your fault but if you die poor it’s your fault.\n If you work with determination and with perfection, success will follow.\n If you dont build your dream, someone else will hire you to help them build theirs.',

),
Category(
  name: 'Sundar Pichai',
  image: 'images/sundarpichai.jpg',
  qulity: '1.	A CEO must know a bit about everything. A CEO may be an expert on Business Development but he must also know about other functions of the company as Sales, Marketing, Law, Programming, Design, Customer Support, etc to command the respect of employees. Mr Pichai is a team player and is known to walk the extra mile to get things done. He is ground to earth and a perfect Boss.\n A CEO is a visionary, he has to be a cheerleader and an inspiration for getting enormous success. No one can buy respect. Business is all about People and those who respect people and are able to inspire them are the biggest leaders. Mr. Pichai has all these qualities and is a perfect match to be a CEO.\n Success is determined by Passion and the desire to push ones limit. Its all about coming out of ones comfort zone and play hard. There is no shortcut to success and Mr. Pichai proves it.',
  intro: 'As we are closing the decade, the man who is closing the year is "Sundar Pichai", the engineer and now the CEO of both Alphabet as well as Google LLC. Sundar Pichai is known to be an Indian one-man army in the market of business and entrepreneurship.',
  life: 'Sundar Pichai was born on 12 July 1972 in Madurai, Tamil Nadu to a middle-class family. His full name is ‘Sundar Rajan Pichai’. His father Raghunath Pichai General Electric Co. Was a Senior Electrical Engineer. His mother Laxmi Pichai used to work as a stenographer. But he quit this job after the birth of Pichai’s younger brother.',
  carrer: 'On 1 April 2004 Sundar Pichai went to give his interview at Google. The same day the company launched the Testing Version of Gmail. The interviewee asked him some questions regarding Gmail. Initially Pichai could not answer those questions properly. They felt that the interviewers might be making fun of April Fools. But when he was asked to use Gmail, then he could put his ideas openly in front of them. Interviewers were so impressed by his ideas that he was immediately placed on the job. His initial responsibilities at Google were related to Google Toolbar and Search.',
  advice: ' Be open, be impatient, be hopeful\n I grew up without much access to technology',

),
Category(
  name: 'Satya Nadellla',
  image: 'images/satyanadella.webp',
  qulity: 'Bring Clarity is the first principle that Nadella says leaders and managers should adhere to to. “In an ambiguous situation\n  where there cannot be complete information, that is when leadership will matter,” Nadella said in an interview our ability to come into an uncertain time and an uncertain future and bring about clarity is key.”\n   Generate energy is the second principle Nadella advocates. “There is no simple thing that is always under your control so the idea is that you have got to create energy all around you,” he noted.\n   The third and most important is to deliver success. Nadella had said that great leaders can’t expect circumstances to beperfect before they deliver success. He said that leaders can never say that one has to first get rid of all the constraints to be “perfect”.',
  intro: '“We must respond to opportunities before they become conventional wisdom.”',
  life: 'Satya was born into a family that was based in Hyderabad, Andhra Pradesh which is now known as Telangana. Bukkapuram Nadella Yugandher his father was a Civil Servant of the Indian Administrative Service.\n   Satya, after completing his schooling at the Hyderabad Public School went on to complete his Bachelor’s degree in Electrical Engineering from the Manipal Institute of Technology in 1988.Now Satya was very clear in the head that he wanted to build things in life, but didn’t really know how to go about it. Yes, he did know that computer science was what he wanted to take up, but since the course didn’t hold that much importance at Manipal University, he decided to go with Electrical Engineering, which became a great way for him to discover his true passion.',
  carrer: 'As usual, the interview process took around eight hours and was very exhausting. In the interview, Satya Nadella was asked to code on screen and as everything went well, he was very confident that he will secure a job at Microsoft.\n   But this confidence couldn’t last long because he failed to properly answer the final question of the interview. Richard Tait asked Satya Nadella that what will be his action if he saw a baby laying on the street and crying.\n   Initially, he felt that this question was related to some unknown algorithm which he missed reading. Finally, he answered that he would call the emergency phone number, 911. After listening to Satya Nadella’s answer, the interviewer got up and escorted him out and said that he should first pick the baby up and give it a hug and also advised him to develop some empathy.',
  advice: 'The Smokejumper Who Failed to Build Trust\n Books as Mental Simulators\n Learn-it-All Culture  ',

),
Category(
  name: 'Shantanu Narayen',
  image: 'images/hantanu.png',
  qulity: 'Great man',
  intro: '"If you can connect all the dots between what you see today and where you want to go, then its probably not ambitious enough or aspirational enough."\n    Adobe is one of those ubiquitous software technologies that’s everywhere, running literally everything. From the Youtube videos to the simplest of mobile apps, everything needs a touch of Adobe. The brain behind Adobe, the man who runs the company, Shantanu Narayen is much like Adobe itself. Quiet, intelligent and everywhere. Shantanu isn’t just the CEO of Adobe.',
  life: 'Narayen was born in Hyderabad, the City of Pearls in India. His father owned a plastics business. He studied in the local Hyderabad Public Schooland then went on complete his graduation in electronics from the Osmania University. He then immigrated to the United States getting both his Management and Masters in Computer Science from University of Berkeley and Bowling Green University respectively. Up until then, Shantanu Narayen’s life was pretty much like any other Indian immigrant.',
  carrer: 'Just like most great people who belong to the software or internet field of work, Shantanu Narayen started off his career at the Apple. Post that, after a stint as a director of the Silicon Graphics, he co-founded Pictra Inc., a company that was one of the first internet photo sharing companies of the world. Soon after that, he took up a job as the Vice President in Adobe. It was while trying to sell his Pictra to Adobe that he landed a job. No, he did not succeed in selling the company to Adobe though. While working at Adobe, he quickly climbed the ladder and was made the CEO within a span of just ten years.',
  advice: 'Round out tech skills\n Think outside the box\n Scale your impact\n Leaders who redefine',

),
Category(
  name: 'Sachin Tendulkar ',
  image: 'images/sachintendulkar.jpg',
  qulity: ' Leave your ego at the door\n Do not dwell\n Listen to yourself\n Look for strong partnerships\n Don t be afraid to ask for help',
  intro: '     “Don t stop chasing your dreams, because dreams do come true.”\n  Sachin Tendulkar is widely regarded as one of the world’s greatest cricketers. Renowned for his incredible batting skills and his penchant for record-breaking one-day scoring, Sachin Tendulkar’s immense success in cricket is unmatched by other international players, making him a true star for the sport',
  life: 'Sachin Tendulkar was born in Dadar, Mumbai to Ramesh Tendulkar, a marathi novelist and his wife, Rahni, who worked in the insurance industry. He was named after Sachin Dev Barman, Ramesh Tendulkar s favourite music director in bollywood. He has two older half siblings, from his father s first marriave, and a sister. \n   As a young child, Sachin Tendulkar grew up in Mumbai. His parents were relatively modest and middle class, offering Sachin Tendulkar reasonable educational options and a potentially bright future. However, Sachin Tendulkar took his education as an obligation instead of as an opportunity, and was known as a bully in his early years',
  carrer: 'Ramakant immediately noticed Sachin’s talent, and recommended that he move to a new high school with a more advanced cricket program. Sachin followed his advice, moving to the new school shortly after. Here, he finally found a group of players that had the drive and ability to challenge him and help him improve his skills further. Sachin devoted his life to cricket with an intensity level and drive that few would ever match. He would spend hours in the training grounds after school, creating a betting system with his fellow players to keep himself motivated. He would place one rupee on the top of the stumps, and challenge players to bowl him out',
  advice: ' It all starts with #LoveWhatYoDo\n Discipline and preparation\n Ability to evolve\n Ability to handle pressure',

),
Category(
  name: 'Mahendra Singh Dhoni',
  image: 'images/msdhoni.jpg',
  qulity: ' You will have to keep following and be persistent with your dreams.\n No matter what working towards your goal should only be your sole aim.\n You will have to look beyond complexities and small obstacles that may interfere in your life.\n Before letting others trust you, you must be able to trust your own skills.\n Also, others can be only confident of you if you are confident in yourself.\n Understand that what is the most important thing to you, and then keep focusing on it until you achieve the same.\n Look at the bigger and brighter side of the scenario.',
  intro: '“ My goal is not to be better than anyone else, but to be better then I used to be”\n   Mahendra Singh Dhoni, better known as MS Dhoni, is arguably the greatest team captain in Indian cricketing history. He is considered as the best cricketer in India. The 39-year old is known for his calm, collected attitude on the field and his bold gambles during the game, earning him the monikers “Captain Cool” and “Captain Extraordinary”.',
  life: '  Mahendra Singh Dhoni was born on July 7, 1981 at Ranchi, Jharkhand located in the east corner of India. He studied at DAV Jawahar Vidya Mandir where he was keenly interested in football and badminton.\n   MS Dhoni comes from a typical family. His father Pan Singh, worked for MECON and his mother Devki Devi is a housewife. He has an elder brother, Narendra Singh Dhoni, who is a politician, and a sister, Jayanti Gupta, who is a teacher.',
  carrer: 'He was able to perform wicket keeping especially well which allowed him entry into a local cricket club called the Commando cricket club where he played from 1995-1998. In the 1997/98 season, his superb performances in the Vinoo Mankad Under-16 Championship attracted the selector s eye.He was made the captain of the ODI team in 2007 and the Test team in 2008. In 2009, he scored 1198 runs in 24 innings at an average of 70.43 to be the highest scorer of the year in ODIs.Dhoni is the successful captain that India ever had. He led India to 27 Test match victories in 60 Tests and 107 ODI wins in 194 ODIs as a captain. He captained 70 T20 matches and he had 40 wins in his account.',
  advice: ' Keep it simple, be honest, devote yourself to something and be focused on that.\n Be Practical and take calculated risks in life\n Be Proud of who you are.\n Manage your time effectively and always focus on quality, not quantity\n Don’t take the pressure.\n Be fearless and calm.\n Be responsible.\n Don’t blame others. Improve yourself.',

),
Category(
  name: 'Cristiano Ronaldo',
  image: 'images/ronaldoo.jpg',
  qulity: '	Believe in Yourself\n Work Hard\n Say to yourself that you are the best\n Never let the critics beat you down\n Always set goals\n Be very professional and always look for improving yourself during trainings\n Be optimistic',
  intro: '“Your love makes me strong, your hate makes me unstoppable.”\n   Cristiano Ronaldo is the world renowned Portuguese professional footballer who was named the greatest Portuguese player of all time by the Portuguese Football federation.  He is also considered by legions of soccer fans all over the world to be the best of all time',
  life: 'As a child, he shared a room with three of his siblings due to their poor financial circumstances.  And although he came from household that was barely getting by financially, he had time to play, and dreamt of greater things. Being born and raised in remote island known as Madeira, an autonomous region of Portugal, his life early on revolved around soccer.\n    Cristiano wasn’t born a legend, but he did something early on which most likely impacted the trajectory of his life.  He decided at a young age to be the best in the world',
  carrer: 'In just six short years after leaving his hometown and his family, his talent, dedication to training, and prowess on the pitch (field), would have him become the youngest player ever to sign a contract with Europe’s most prestigious professional football league,  ‘Manchester United’.  And this transaction would become one of the most expensive transfer contracts to date.  In 2003, Cristiano Ronaldo made history.Since then Cristiano Ronaldo has managed to rack up accolade after accolade after accolade.  Here are just  a handful of his biggest accomplishments:',
  advice: ' Set yourself goals. It will help to keep you focused and work towards something\n Proper sleep is very important. I go to bed early and I get up early.\n Mix it up. I recommend a combination of cardio (running and rowing) and weight training to ensure that workouts target all areas of the body and increase both strength and stamina.\n You can do an abs workout in your bedroom when you wake up in the morning or before you go to bed.\n Eat a high protein diet, with lots of wholegrain carbs, fruit and vegetables and avoid sugary foods.\n Drinking water is so important. I also avoid alcohol.',

),
Category(
  name: 'Lionel messi',
  image: 'images/messii.jpg',
  qulity: ' Self-discovery\n Determination\n Perseverance\n Personal development of his talent\n Optimism\n Dedication and Focus',
  intro: 'I have fun like a child in the street. When the day comes when I’m not enjoying it, I will leave football.\n     Lionel messi is God of Foodball. He is also Best Player of world. Technically perfect,he brings together selfishness,pace , composure and goals to make him Number One',
  life: 'Lionel Messi was born in Argentina and comes from a poor family. His father was a factory steel worker and his mother was a part time cleaner. Messi developed a great passion for football very early in his life, so at the age of 5 he started playing football for a local club coached by his father and when he was 8, he joined Newell Old Boys Club.\n      He dreamed of becoming a professional football player, but that dream started to fall apart when he was diagnosed with growth hormone deficiency. This meant that he was physically unable to grow unless he received special expensive therapy that cost 900 dollar a month. Unfortunately His parents couldn’t afford it. And the club that he was playing for refused to pay for the therapy',
  carrer: 'At 16 he made his first appearance for Barcelona. The following year, At just 17 years of age, he became the youngest player to appear in La Liga when he debuted in October 2004. Six months later, on May 1, 2005, he marked himself in the record books as the youngest player to score a goal for the franchise.\n   Messi has gone on to win five league titles with Barca. As a successor of Ronaldinho’s number 10 jersey, he scored 38 goals in the 2008/09 season, earning himself his first FIFA Player of the Year Award. Messi surpassed the 38-goal tally in the two following seasons, scoring 45 and 50 respectively as Barca won the championship, while also securing their third Champions League in six seasons',
  advice: 'Fight For Your Dreams\n It’s not all about physical ability, but it’s about mental ability\n Sacrifices And Hard Work\n No sickness can stop you to achieve your goal\n It doesn’t matter if you come from a humble background.\n Capitalising Opportunity',

),
Category(
  name: 'The Rock',
  image: 'images/rockk.jpg',
  qulity: 'Have a Sense of Purpose\n Persistence Pays\n Without Control, Strength Can Become Weakness\n Work Hard, Always\n See the Signs Around You\n In Doubt, Go Back to Basics',
  intro: '“All success begins with self-discipline. It starts with you.”\n   The best remembered for his wrestling career and his unchallengeable title known as ‘The Rock’. One of the greatest and most popular WWE wrestlers during his time, things never went easy for The Rock and he established his name’s worth by winning seven consecutive WWE championships.',
  life: 'Dwayne Douglas Johnson ‘The Rock’ born in Hayward, California on May 2, 1972  Born to a father of Canadian origin and a mom of Samoan, Dwayne attended Richmond Road Primary School in New Zealand and spent 10th Standard at President William McKinley High School in Honolulu, Hawaii. Right from his youth days, Dwayne was famous and well praised for his sportsman capabilities.He was also a part of the school’s track and field and wrestling teams',
  carrer: 'the sequence name of his grandfather’s and father’s ring names, Johnson made his WWE debut as Rocky Maivia and aside from that, he was also given the nickname “The Blue Chipper ”. Dwayne won several matches and championships against his fellow wrestlers, some of whom were as leading as The Brooklyn Brawler, Triple H etc. However, his work as a wrestler was not the smoothest one in his life\n   Johnson appeared in many other films, including the fifth and six parts of The Fast and the Furious series. He has many other movie credits in his pocket like G.I. Joe: Retaliation, Fast Five, Journey 2: The Mysterious Island, Fast & Furious 6, Snitch, etc.',
  advice: ' Be Electrifying and Charismatic\n Know What You Want\n Be Absolutely Committed to Your Work\n Be Yourself\n Have Faith and Follow Your Heart\n Improve Yourself\n Never be Afraid to Fail\n You Need a Coach\n Be With a Great Team\n Be Playful and Enjoy Life',

),
Category(
  name: 'Usain Bolt',
  image: 'images/usaib.jpg',
  qulity: ' Start like I say, not as I do\n Don’t rush to ‘run tall\n You need power for the glory\n A strong core helps you score\n It’s a sprint, not a marathon\n Eat like a champion',
  intro: '"For me, I m focused on what I want to do. I know what I need to do to be a champion, so Im working on it."\n  Jamaica s Usain Bolt is an Olympic legend who has been called "the fastest man alive" for smashing world records and winning multiple gold medals at the 2008, 2012 and 2016 Summer Games',
  life: 'At the age of 15, Bolt took his first shot at success on the world stage at the 2002 World Junior Championships in Kingston, Jamaica, where he won the 200-meter dash, making him the youngest world-junior gold medalist ever. Bolt feats impressed the sports world, and he received the International Association of Athletics Foundation’s Rising Star Award that year, boosting the recognition of a young man soon to be known as "Lightning Bolt.',
  carrer: 'By the age of 15, Bolt had grown to 1.96 metres (6 ft 5 in) tall, and already stood out among his peers. At that early age, he won a gold medal in the 200 meters in a time of 20.61 seconds at the 2002 World Junior Championships. His win made him the youngest world-junior gold medallist ever. At the Summer Olympics, 2008, Bolt won three gold medals in the 100 meters (9.69 seconds), 200 meters (19.30 seconds), and 4x100 meter relay (37.10 seconds), all world-record times',
  advice: ' Let your purpose drive you\n Be clear on what you want your legacy to be\n Its all about that championship moment\n Reframe your category to maximize growth\n Focus and fun go together\n Overcome doubters with unbridled self-confidence',

),
Category(
  name: 'Warren Buffett',
  image: 'images/warren.png',
  qulity: ' Be selfless and don’t expect anything in return\n Be empathetic\n Make work enjoyable and fun\n Treat others the way they want to be treated\n Follow your passion',
  intro: 'Warren Buffett is a self-made billionaire. His successful investment business makes him one of the most respected men in the world',
  life: 'Warren Edward Buffett was born on August 30, 1930, to his mother Leila and father Howard. At only six years old, Buffett purchased six-packs of Coca-Cola from his grandfather s grocery store for twenty-five cents and resold each of the bottles for a nickel, pocketing a five-cent profit. While other children his age were playing hopscotch and jacks, Warren was making money. Five years later, Buffett took his first step into the world of high finance.\n   At eleven years old, he purchased three shares of Cities Service Preferred at 38 dollar per share for both himself and his older sister, Doris',
  carrer: 'Buffett and Susie moved into a house in the suburbs of New York. Buffett spent his days analyzing S&P reports, searching for investment opportunities. It was during this time that the differences between the Graham and Buffett philosophies began to emerge.\n  Buffett became interested in how a company worked—what made it superior to competitors. Graham simply wanted numbers, while Warren was more interested in a company s management as a major factor when deciding to invest',
  advice: ' Mental aptitude (Being seriously smart)\n Early start (If something takes a long time to achieve, you better start early)\n Being a learning machine (Keep learning and learning)\n Being correctly trusted by people\n Avoiding envy, jealousy, self-pity, vengeance, and extreme ideology',

),
Category(
  name: 'Walt Disney',
  image: 'images/wallt.jpg',
  qulity: ' He did not give up\n innovative and creative\n risk taker.\n He was an innovator\n Disney was passionate about what he was doing.',
  intro: 'Walt Disney was among the most creative man ever lived on this planet whose huge dreams actually came true. He along with his brother Roy O. Disney co-founded ‘The Walter Disney Company’ commonly known as ‘Disney’ on October 16, 1923. It is currently the second largest cable and broadcasting company in terms of revenue.',
  life: 'Walter Disney was born on December 5, 1901 in Chicago, to Elias Charles Disney and Flora Call Disney. His childhood days were interrupted because his family moved from  Chicago to Missouri and once again to Kansas City. He also worked as a newspaper boy to support his family and didn’t have much time for schools. Although he started the Park School of Marceline in fall, 1909 together with his younger sister Ruth.\n    In his free time, he went to the theatre where he studied vaudeville. He was a big fan of Charlie Chaplin and loved drawing cartoons for school paper',
  carrer: 'In 1928, to recover the loss from Oswald the Lucky Rabbit, Disney came with the idea about a mouse character later named as Mickey Mouse. The character Mickey Mouse was breakthrough both in terms of money and popularity. Disney himself provided the sound for Mickey Mouse until 1947. Disney continued to produce cartoons with Mickey Mouse and other characters and began the Silly Symphony series with Columbia Pictures signing on as Symphonies distributor in August 1929.\n     Walt Disney with his brother Roy O. Disney started “The Walt Disney Company” on October 16, 1923, under the name Disney Brother Cartoon Studio. It also operated on the names The Walt Disney Studio and Walt Disney Production before officially changing its name to “The Walt Disney Company”. Walt Disney worked as a cartoonist in Pesmen-Rubin Art Studio, a job which he got with the help of his brother Roy.',
  advice: 'You must be a salesman.\n Leadership is inspiration, innovation and focus\n Always be constantly improving.\n Develop a high tolerance for risk.\n Change your attitude towards failure.\n Believe in yourself, even when everyone say’s you’re crazy.\n Resiliency is an entrepreneur’s best friend.',

),
Category(
  name: 'Henry Ford ',
  image: 'images/fors.jpg',
  qulity: ' Be so good at what you do that people think you invented it.\n Failures are opportunities.\n Be as strong behind the scenes as you are anywhere else.\n Don’t be a showoff.\n Don’t only be in the business of making money',
  intro: ' “If there is any one secret of success, it lies in the ability to get the other person’s point of view and see things from that person’s angle as well as from your own.”\n   Henry Ford is one of the most renowned entrepreneurs in history. He optimized transportation and forever changed the United States automobile industry. His innovative manufacturing process produced low-cost, reliable vehicles, while simultaneously keeping his workers well-paid and loyal',
  life: 'Ford was born on 30 July, 1863 in Greenland Township, Michigan. When he was young, he used to dismantle and reassemble his friends timepieces and watch, gifted by his father, which gave him reputation of a watch repairman.\n   In 1876, Henry lost his mother and did not wanted to live and work on farm without his mother.In 1879, Ford at age of 16, left home against his father’s will to work as an apprentice machinist at a ship building firm in Detroit',
  carrer: 'Ford formed his own company named Detroit Automobile Company. But, he was forced to shut it down as the automobiles produced by company did not perform well in market. After failed efforts, he soon started working to improve the quality of his automobiles. In 1901, he successfully developed 26 – horsepower automobile. In 1901, he teamed up with stockholders of Detroit Company to form Henry Ford Company\n   Ford was sued by his stockholders and had to leave the company. The company was later renamed as Cadillac Automobile Company. The failure of two venture did not stop him living his dream and passion. He continued to work and build several racing cars including “999” racer car.',
  advice: ' Seek Advice from Others\n Invest in What Works\n Create For Everyone\n “Don’t find fault; find a remedy.”\n Always Produce High Quality Work\n Have Passion For What You Do\n Anything is possible',

),

];